// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using client_management_asp_core_api.Models;

namespace client_management_asp_core_api.Migrations
{
    [DbContext(typeof(ClientManagementDBContext))]
    [Migration("20210131003247_CreateClientMigrations")]
    partial class CreateClientMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("client_management_asp_core_api.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("_Contact")
                        .HasColumnName("Contact")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("client_management_asp_core_api.Models.PaymentDetail", b =>
                {
                    b.Property<int>("paymentDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CardNmber")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("cardOwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("expirationDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("securityCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("paymentDetailId");

                    b.HasIndex("ClientId");

                    b.ToTable("PaymentDetails");
                });

            modelBuilder.Entity("client_management_asp_core_api.Models.PaymentDetail", b =>
                {
                    b.HasOne("client_management_asp_core_api.Models.Client", "Client")
                        .WithMany("PaymentDetails")
                        .HasForeignKey("ClientId");
                });
#pragma warning restore 612, 618
        }
    }
}
